version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mounting default.conf here
      - ./:/var/www/html # Application files

    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - data

  php-fpm:
    build: ./php
    volumes:
      - ./:/var/www/html # Application files
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - data

  data:
    image: mysql:latest
    container_name: data
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2basic
      MYSQL_PASSWORD: yii2basic
      MYSQL_ROOT_PASSWORD: yii2basic

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: data
      MYSQL_PASSWORD: yii2basic
      MYSQL_ROOT_PASSWORD: yii2basic
    ports:
      - "8080:80"
    depends_on:
      - data

  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   container_name: keycloak
  #   environment:
  #     KC_DB: mysql
  #     KC_DB_URL_HOST: data
  #     KC_DB_URL_DATABASE: yii2basic
  #     KC_DB_USERNAME: yii2basic
  #     KC_DB_PASSWORD: yii2basic
  #     KC_HOSTNAME: localhost
  #     KC_BOOTSTRAP_ADMIN_USERNAME: test
  #     KC_BOOTSTRAP_ADMIN_PASSWORD: test
  #   command: start-dev
  #   ports:
  #     - "9999:9999"
  #   depends_on:
  #     - data

volumes:
  db_data:
