version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Конфигурация Nginx
      - ./:/var/www/html # Файлы приложения
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - data

  php-fpm:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/html # Файлы приложения
    depends_on:
      - data

  data:
    image: mysql:latest
    container_name: data
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2basic
      MYSQL_PASSWORD: yii2basic
      MYSQL_ROOT_PASSWORD: yii2basic
    volumes:
      - db_data:/var/lib/mysql # Использование именованного тома для хранения данных
    ports:
      - "3306:3306"

  phpmyadmins:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmins
    environment:
      PMA_HOST: data
      PMA_USER: yii2basic
      PMA_PASSWORD: yii2basic
      MYSQL_ROOT_PASSWORD: yii2basic
    ports:
      - "8080:80"
    depends_on:
      - data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    command: [ "start-dev" ]
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://data:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
  
    ports:
      - "8081:8080"
    depends_on:
      - data

volumes:
  db_data: # Именованный том для данных MySQL
